# Generated by Django 2.2.3 on 2020-04-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wxuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unionid', models.CharField(max_length=32)),
                ('openid', models.CharField(max_length=32)),
                ('stats', models.CharField(max_length=32)),
                ('userid', models.CharField(max_length=32)),
                ('create_time', models.CharField(max_length=32)),
                ('upeate_time', models.CharField(max_length=32)),
            ],
        ),
    ]
