# Generated by Django 2.2.3 on 2020-04-14 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weixin_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wxuser',
            table='book',
        ),
    ]
