# Generated by Django 2.2.3 on 2020-04-14 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weixin_web', '0002_auto_20200414_1911'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wxuser',
            table='wxuser',
        ),
    ]
