# Generated by Django 3.0 on 2020-03-08 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chicken_soup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=50000)),
                ('create_by', models.CharField(max_length=32)),
                ('create_date', models.CharField(max_length=32)),
                ('upeate_by', models.CharField(max_length=32)),
                ('upeate_date', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Love',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=50000)),
                ('create_by', models.CharField(max_length=32)),
                ('create_date', models.CharField(max_length=32)),
                ('upeate_by', models.CharField(max_length=32)),
                ('upeate_date', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=50000)),
                ('create_by', models.CharField(max_length=32)),
                ('create_date', models.CharField(max_length=32)),
                ('upeate_by', models.CharField(max_length=32)),
                ('upeate_date', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=500)),
                ('play_url', models.CharField(max_length=50000)),
                ('picture_url', models.CharField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='Sentimental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=50000)),
                ('create_by', models.CharField(max_length=32)),
                ('create_date', models.CharField(max_length=32)),
                ('upeate_by', models.CharField(max_length=32)),
                ('upeate_date', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Struggle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=50000)),
                ('create_by', models.CharField(max_length=32)),
                ('create_date', models.CharField(max_length=32)),
                ('upeate_by', models.CharField(max_length=32)),
                ('upeate_date', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('Mobile_phone', models.CharField(max_length=32)),
                ('create_by', models.CharField(max_length=32)),
                ('create_date', models.CharField(max_length=32)),
                ('upeate_by', models.CharField(max_length=32)),
                ('upeate_date', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='wxuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unionid', models.CharField(max_length=32)),
                ('openid', models.CharField(max_length=32)),
                ('stats', models.CharField(max_length=32)),
                ('userid', models.CharField(max_length=32)),
                ('create_time', models.CharField(max_length=32)),
                ('upeate_time', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('create_by', models.CharField(max_length=32)),
                ('create_date', models.CharField(max_length=32)),
                ('upeate_by', models.CharField(max_length=32)),
                ('upeate_date', models.CharField(max_length=32)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxtest.UserType')),
            ],
        ),
    ]
